### ISSUE TITLE
build

### ISSUE THREAD

**Issue by ddkwork** [AlbinoDrought/wails-android-test#1]
hi，i am Stuped with your readme with some error

![3K~L@2IBYNJO%@7~}HE56PB.png](https://github.com/AlbinoDrought/wails-android-test/assets/19886504/18c0b9ec-6a23-4869-abe6-8957b67da34b)

![)2J`HXSE7R[1_ISOVUQOWM1.png](https://github.com/AlbinoDrought/wails-android-test/assets/19886504/76022446-e764-474b-99f8-fb848ef478a4)

it support Android sdk and ndk 26 version？

**Comment by AlbinoDrought** [comment]
Hello, it appears you may be using the official version of the Wails CLI tool (v2.6.0). This repository needs a special version of the Wails CLI.

Step 3 in this repository's readme was incorrect. [I've updated it, can you please retry](https://github.com/AlbinoDrought/wails-android-test)? After that, step 4 should install the modified Wails CLI. When running `wails version` you should see `v2.0.0-beta.44.2`:

![image](https://github.com/AlbinoDrought/wails-android-test/assets/852873/49684f74-ee12-40d9-8a8c-8839c8beeef7)

In particular, the commands are:

3: `git submodule update --init --recursive`
4: `pushd wails/v2/cmd/wails && go install && popd`

**Comment by ddkwork** [comment]
> Hello, it appears you may be using the official version of the Wails CLI tool (v2.6.0). This repository needs a special version of the Wails CLI.
> 
> Step 3 in this repository's readme was incorrect. [I've updated it, can you please retry](https://github.com/AlbinoDrought/wails-android-test)? After that, step 4 should install the modified Wails CLI. When running `wails version` you should see `v2.0.0-beta.44.2`:
> 
> ![image](https://github.com/AlbinoDrought/wails-android-test/assets/852873/49684f74-ee12-40d9-8a8c-8839c8beeef7)
> 
> In particular, the commands are:
> 
> 3: `git submodule update --init --recursive`
> 4: `pushd wails/v2/cmd/wails && go install && popd`
> 

No, it was the day I found out that the command was wrong, and then I did it manually: clone your repository, delete the wails directory, then git clone -b hack/Android branch, and finally cd to the cmd directory to execute go install. Then I ran into the tmp directory permissions when building aar's makefile that seemed to be incorrect, even though chmod 777 gave it permissions. Finally, I changed the console's tmpdir environment variable to the current directory, and finally installed the latest Android SDK and NDK19 version under Manjaro Linux through Aur resources and yay commands, and generated the AAR file, but by the last step gradle WebView, no matter how I tried to compile it failed
